name: boxpend_flutter_android_app
description: A delivery app built using the Flutter & GetX.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.1.1
  heroicons: ^0.7.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/onboarding1.svg
    - assets/images/onboarding2.svg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 700
