name: boxpend_flutter_android_app
description: A delivery app built using the Flutter & GetX.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  get: ^4.6.5
  get_storage: ^2.1.1
  heroicons: ^0.7.0
  image_picker: ^1.0.1
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.svg
    - assets/images/onboarding1.svg
    - assets/images/onboarding2.svg
    - assets/json/policy.json
    - assets/json/terms.json


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700
